title: "Ericâ€™s Blog"
description: "Blogging about code, projects, and photos"
url: "https://dong0085.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache   
  - jekyll-paginate

# Blog settings
paginate: 5
paginate_path: "/blog/page:num/"

# Collections 
collections:
  projects:
    output: true
    permalink: /projects/:title/
